# Site settings
title: Xamarin Forms Tutorials
header-img: img/home-bg.jpg
email: romancingthecode@gmail.com
copyright_name: Romancing the Code
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/xamarinforms"
url: "http://xamarinforms.info"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
